# Duration between API calls (in hours)
poll_interval: 2

# Number of plays required to add track to playlist
valid_listenTimes: 3

# Maximum play count limit for songs
fmap_limit: 7

# Threshold value for decay process
decay_threshold: 15